/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
 */

package projecteuler;

public class num002_even_fibonacci {
	//a fibonacci number is made up of two numbers
	public static void main(String[] args) {
		int num1 = 1;
		int num2 = 2;
		//the total of the even fibonacci numbers
		int total = num2; //2 to start with
		//swapping values for a new fibonacci number
		int swap = 0;
		boolean canContinue = true;
		//main fibonacci loop
		while (canContinue) {
			//num1 becomes num2,
			//num2 becomes num1 + num2
			//this is to progress with subsequent
			//fibonacci numbers
			swap = num1 + num2;
			num1 = num2;
			num2 = swap;
			//stop at values over 4 million
			if (num2 > 4000000) {
				canContinue = false;
			} else {
				if (num2 % 2 == 0) {
					total += num2;
				}
			}
		}
		System.out.println("Sum: " + total);
	}	
}